---
- name: Setting up our cloud
  ansible.builtin.import_playbook: ./system/import.yaml
  tags: [system]

- name: Installing required packages
  ansible.builtin.import_playbook: ./packages/import.yaml
  tags: [packages]

- name: Setting up security
  ansible.builtin.import_playbook: ./security/import.yaml
  tags: [security]

- name: Installing kubernetes-full
  ansible.builtin.import_playbook: ./kubernetes/import.yaml
  tags: [kubernetes]
