---
- name: Installing CRI-O // infra/ansible/playbook/packages/cri/cri-o/install.yaml
  hosts: all
  become: true

  tasks:
    - name: Adding a CRI-O repository
      ansible.builtin.copy:
        src: ./cri-o.repo.j2
        dest: /etc/yum.repos.d/cri-o.repo
        mode: "644"
        remote_src: false

    - name: Install CRI-O
      ansible.builtin.dnf:
        name: cri-o
        state: present

    - name: Launching CRI-O service
      ansible.builtin.systemd_service:
        name: crio
        state: started
        enabled: true
