---
- name: Installing CNI Cilium in a cluster an helm // infra/ansible/playbook/kubernetes/helm/cni/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Add Cilium chart repository to Helm
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/network/cni/values.yaml
        dest: /home/user/cilium.yaml
        mode: "644"
        remote_src: false

    - name: Install Cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        values_files:
          - /home/user/cilium.yaml

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/cilium.yaml
        state: absent

    - name: Delete previous CNI
      ansible.builtin.file:
        path: /usr/local/bin/cilium
        state: absent
