---
- name: Installing gitlab in a cluster // infra/ansible/playbook/kubernetes/helm/gitlab/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Add gitlab chart repository to Helm
      kubernetes.core.helm_repository:
        name: gitlab
        repo_url: https://charts.gitlab.io/

    - name: Copy the required values.yaml gitlab-ce
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/gitlab/values.yaml
        dest: /home/user/gitlab-ce.yaml
        mode: "644"
        remote_src: false

    - name: Install gitlab-ce
      kubernetes.core.helm:
        name: gitlab
        chart_ref: gitlab/gitlab
        release_namespace: nm-gitlab
        values_files:
          - /home/user/gitlab-ce.yaml

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/gitlab-ce.yaml
        state: absent
