---
- name: Installing grafana in a cluster // infra/ansible/playbook/kubernetes/helm/monitoring/grafana.yaml
  hosts: masters
  become: true

  tasks:
    - name: Add Grafana chart repository to Helm
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/monitoring/grafana/values.yaml
        dest: /home/user/grafana.yaml
        mode: "644"
        remote_src: false

    - name: Install Grafana
      kubernetes.core.helm:
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: nm-monitoring
        values_files:
          - /home/user/grafana.yaml

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/grafana.yaml
        state: absent
