---
- name: Create password secret // infra/ansible/playbook/kubernetes/default/space/password.yaml
  hosts: masters
  become: true
  vars_files:
    - ../../../secrets/secrets.yaml

  tasks:
    - name: Create password secret in each namespace gitlab
      ansible.builtin.shell: |
        set -o pipefail
        kubectl create secret generic gitlab-secret-password \
          --from-literal=password="{{ password }}" \
          -n nm-gitlab \
          --dry-run=client -o yaml | kubectl apply -f -
      changed_when: false
      no_log: true
