---
- name: Adding a new user // infra/ansible/playbook/security/users/admin.yaml
  hosts: all
  become: true

  tasks:
    - name: New user without root rights
      ansible.builtin.user:
        name: admin
        create_home: false
        shell: /bin/bash
        uid: 356
        groups: root
