---
- name: Adding a new user // infra/ansible/playbook/security/users/user.yaml
  hosts: all
  become: true

  tasks:
    - name: New user without root rights
      ansible.builtin.user:
        name: user
        create_home: true
        shell: /bin/bash
        uid: 1000
