---
- name: Install Gateway // infra/ansible/playbook/kubernetes/default/gateway/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Download Gateway file
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
        dest: /tmp/gateway-install.yaml
        mode: "0644"

    - name: Installing Gateway API
      kubernetes.core.k8s:
        src: /tmp/gateway-install.yaml
        state: present

    - name: Remove Gateway file
      ansible.builtin.file:
        path: /tmp/gateway-install.yaml
        state: absent
