---
- name: Install traefik in cluster // infra/ansible/playbook/kubernetes/helm/traefik/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Add Traefik Labs chart repository to Helm
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://traefik.github.io/charts

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/traefik/values.yaml
        dest: /home/user/traefik.yaml
        mode: "644"
        remote_src: false

    - name: Install traefik
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: nm-traefik
        values_files:
          - /home/user/traefik.yaml
        wait: true

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/traefik.yaml
        state: absent
