---
- name: Installing ArgoCD // infra/ansible/playbook/kubernetes/helm/argo/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Add ArgoCD chart repository to Helm
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/argocd/values-argo.yaml
        dest: /home/user/argo-standart.yaml
        mode: "644"
        remote_src: false

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/argocd/values-rollouts.yaml
        dest: /home/user/argo-rollouts.yaml
        mode: "644"
        remote_src: false

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/argocd/values-events.yaml
        dest: /home/user/argo-events.yaml
        mode: "644"
        remote_src: false

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/base/argocd/config.yaml
        dest: /home/user/argo-config.yaml
        mode: "644"
        remote_src: false

    - name: Install ArgoCD
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: nm-argo
        values_files:
          - /home/user/argo-standart.yaml
        wait: true

    - name: Install Argo Rollouts
      kubernetes.core.helm:
        name: argo-rollout
        chart_ref: argo/argo-rollouts
        release_namespace: nm-argo
        values_files:
          - /home/user/argo-rollouts.yaml
        wait: true

    - name: Install Argo Events
      kubernetes.core.helm:
        name: argo-events
        chart_ref: argo/argo-events
        release_namespace: nm-argo
        values_files:
          - /home/user/argo-events.yaml
        wait: true

    - name: Installing config for argo
      kubernetes.core.k8s:
        src: /home/user/argo-config.yaml
        state: present

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /home/user/argo-standart.yaml
        - /home/user/argo-rollouts.yaml
        - /home/user/argo-events.yaml
        - /home/user/argo-config.yaml
