---
- name: Installing Nexus in a cluster // infra/ansible/playbook/kubernetes/helm/nexus/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Add Nexus chart repository to Helm
      kubernetes.core.helm_repository:
        name: nexus
        repo_url: https://sonatype.github.io/helm3-charts/

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/helm/nexus/values.yaml
        dest: /home/user/nexus.yaml
        mode: "644"
        remote_src: false

    - name: Install Nexus
      kubernetes.core.helm:
        name: nexus
        chart_ref: nexus/nexus-repository-manager
        release_namespace: nm-nexus
        values_files:
          - /home/user/nexus.yaml

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/nexus.yaml
        state: absent
