---
- name: Disable ipv6 // infra/ansible/playbook/system/network/ipv6.yaml
  hosts: all
  become: true

  tasks:
    - name: Disable ipv6 all
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: "1"

    - name: Disable ipv6 default
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: "1"
