---
- name: Installing helm // infra/ansible/playbook/kubernetes/helm/install.yaml
  hosts: masters
  become: true

  tasks:
    - name: Did we install Helm
      ansible.builtin.command: when helm
      changed_when: false
      ignore_errors: true
      register: check_helm

    - name: We get the required .sh file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: "700"
      when: check_helm.rc != 0

    - name: Run the resulting .sh file
      ansible.builtin.command: /tmp/get_helm.sh
      changed_when: false
      when: check_helm.rc != 0
